### PR TITLE
feat: add initial support for Wiim Mini device

### PR DESCRIPTION
**Pull request by akloeckner**
I have recently added a Wiim Mini to my LinkPlay setup and hat to notice, it was not supported by my favorite HA LinkPlay integration. ;-)

So, I read through #72 and #94 and checked @onlyoneme's fork here: https://github.com/onlyoneme/home-assistant-custom-components-wiim . The main change seems to be using `https` and `getStatusEx`.

So, here's a PR integrating this transparently. So, failing http is handled by trying https. So far, this works well on my end.

### CODE REVIEW

**Comment by adamcowan** [comment]
I can confirm works with my LinkPlay devices using a mixture of both HTTP and HTTPS.

**Comment by maxi1134** [comment]
Could this be merged?

**Comment by maxi1134** [comment]
For those wondering, this works with Wiim Pro as well

**Comment by onlyoneme** [comment]
Bear in mind that the Mini will not return song metadata in getPlayerStatus and both Pro and Mini won't return the playback status over http api for some services.

**Comment by akloeckner** [comment]
> Bear in mind that the Mini will not return song metadata in getPlayerStatus and both Pro and Mini won't return the playback status over http api for some services.

Good hint. This might even apply to Arylic devices, as I have seen them not updating timely in Home Assistant sometimes. I'll open an issue here, once I have a better feeling, when this occurs. I already opened an issue with your fork to maybe merge your improvements back here, because I have the feeling you did quite some work on these difficulties.

**Pull request merged**
