### PR TITLE
Adds implementation for `command=playPromptUrl:[URL]`

### PR DESCRIPTION
**Pull request by tfahrenreich**
Command was added in [4.6.4151](https://forum.arylic.com/t/firmware-upgrade-4-6-415145-a30-sa100-wbc65-up2stream-plate-amp-may-11-2022/2156)

Allows TTS (or any media url) to be played without interrupting current playback, further eliminating the need for snapshots

### CODE REVIEW

**Comment by tfahrenreich** [comment]
There seems to be some rules about when this is usable, doesn't work during bluetooth playback.
Should probably wait until the official documentation site is back up.

**Comment by nagyrobi** [comment]
This doesn't work in many other circumstances too. I've tested it locally and it's not ready to be used.

**Comment by tfahrenreich** [comment]
Yeah, the device needs to be in a steaming mode to utilize it seems. 
Will update shortly

**Comment by nagyrobi** [comment]
Not really useful then...

**Pull request closed without merging**
